const ACTION_TYPES = {
    GET_MOVIES_START: 'GET_MOVIES_START',
    GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
    GET_MOVIES_FAILED: 'GET_MOVIES_FAILED',

    GET_CATEGORIZED_MOVIES_START: 'GET_CATEGORIZED_MOVIES_START',
    GET_CATEGORIZED_MOVIES_SUCCESS: 'GET_CATEGORIZED_MOVIES_SUCCESS',
    GET_CATEGORIZED_MOVIES_FAILED: 'GET_CATEGORIZED_MOVIES_FAILED',

    GET_LATEST_TWENTY_MOVIES_START: 'GET_LATEST_TWENTY_MOVIES_START',
    GET_LATEST_TWENTY_MOVIES_SUCCESS: 'GET_LATEST_TWENTY_MOVIES_SUCCESS',
    GET_LATEST_TWENTY_MOVIES_FAILED: 'GET_LATEST_TWENTY_MOVIES_FAILED'
};

export default ACTION_TYPES