const ACTION_TYPES = {
    CREATE_MOVIE: 'CREATE_MOVIE',

    GET_MOVIES_START: 'GET_MOVIES_START',
    GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
    GET_MOVIES_FAILED: 'GET_MOVIES_FAILED',

    GET_MOVIE_NOTIFICATIONS_START: 'GET_MOVIE_NOTIFICATIONS_START',
    GET_MOVIE_NOTIFICATIONS_SUCCESS: 'GET_MOVIE_NOTIFICATIONS_SUCCESS',
    GET_MOVIE_NOTIFICATIONS_FAILED: 'GET_MOVIE_NOTIFICATIONS_FAILED',

    GET_CATEGORIZED_MOVIES_START: 'GET_CATEGORIZED_MOVIES_START',
    GET_CATEGORIZED_MOVIES_SUCCESS: 'GET_CATEGORIZED_MOVIES_SUCCESS',
    GET_CATEGORIZED_MOVIES_FAILED: 'GET_CATEGORIZED_MOVIES_FAILED',

    GET_LATEST_TWENTY_MOVIES_START: 'GET_LATEST_TWENTY_MOVIES_START',
    GET_LATEST_TWENTY_MOVIES_SUCCESS: 'GET_LATEST_TWENTY_MOVIES_SUCCESS',
    GET_LATEST_TWENTY_MOVIES_FAILED: 'GET_LATEST_TWENTY_MOVIES_FAILED',

    GET_TOP_SEARCHED_MOVIES_START: 'GET_TOP_SEARCHED_MOVIES_START',
    GET_TOP_SEARCHED_MOVIES_SUCCESS: 'GET_TOP_SEARCHED_MOVIES_SUCCESS',
    GET_TOP_SEARCHED_MOVIES_FAILED: 'GET_TOP_SEARCHED_MOVIES_FAILED',

    GET_MOST_LIKED_MOVIES_START: 'GET_MOST_LIKED_MOVIES_START',
    GET_MOST_LIKED_MOVIES_SUCCESS: 'GET_MOST_LIKED_MOVIES_SUCCESS',
    GET_MOST_LIKED_MOVIES_FAILED: 'GET_MOST_LIKED_MOVIES_FAILED',
    
    INCREMENT_MOVIE_VIEWS_START: 'INCREMENT_MOVIE_VIEWS_START',
    INCREMENT_MOVIE_VIEWS_SUCCESS: 'INCREMENT_MOVIE_VIEWS_SUCCESS',
    INCREMENT_MOVIE_VIEWS_FAILED: 'INCREMENT_MOVIE_VIEWS_FAILED',

    INCREMENT_MOVIE_SEARCH_COUNT_START: 'INCREMENT_MOVIE_SEARCH_COUNT_START',
    INCREMENT_MOVIE_SEARCH_COUNT_SUCCESS: 'INCREMENT_MOVIE_SEARCH_COUNT_SUCCESS',
    INCREMENT_MOVIE_SEARCH_COUNT_FAILED: 'INCREMENT_MOVIE_SEARCH_COUNT_FAILED',
};

export default ACTION_TYPES