const ACTION_TYPES = {
    CREATE_MOVIE: 'CREATE_MOVIE',

    GET_MOVIES_START: 'GET_MOVIES_START',
    GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
    GET_MOVIES_FAILED: 'GET_MOVIES_FAILED',

    GET_CATEGORIZED_MOVIES_START: 'GET_CATEGORIZED_MOVIES_START',
    GET_CATEGORIZED_MOVIES_SUCCESS: 'GET_CATEGORIZED_MOVIES_SUCCESS',
    GET_CATEGORIZED_MOVIES_FAILED: 'GET_CATEGORIZED_MOVIES_FAILED',

    GET_LATEST_TWENTY_MOVIES_START: 'GET_LATEST_TWENTY_MOVIES_START',
    GET_LATEST_TWENTY_MOVIES_SUCCESS: 'GET_LATEST_TWENTY_MOVIES_SUCCESS',
    GET_LATEST_TWENTY_MOVIES_FAILED: 'GET_LATEST_TWENTY_MOVIES_FAILED',
    
    INCREMENT_MOVIE_VIEWS_START: 'INCREMENT_MOVIE_VIEWS_START',
    INCREMENT_MOVIE_VIEWS_SUCCESS: 'INCREMENT_MOVIE_VIEWS_SUCCESS',
    INCREMENT_MOVIE_VIEWS_FAILED: 'INCREMENT_MOVIE_VIEWS_FAILED',
};

export default ACTION_TYPES