const ACTION_TYPES = 
{
    ADD_TO_RECENT_WATCHES_START: 'ADD_TO_RECENT_WATCHES_START',
    ADD_TO_RECENT_WATCHES_SUCCESS: 'ADD_TO_RECENT_WATCHES_SUCCESS',
    ADD_TO_RECENT_WATCHES_FAILED: 'ADD_TO_RECENT_WATCHES_FAILED',

    BROADCAST_CREATE_PROFILE: 'BROADCAST_CREATE_PROFILE',
    BROADCAST_DELETE_PROFILE_BY_ID: 'BROADCAST_DELETE_PROFILE_BY_ID',
    BROADCAST_UPDATE_PROFILE: 'BROADCAST_UPDATE_PROFILE',

    CREATE_PROFILE_START: 'CREATE_PROFILE_START',
    CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
    CREATE_PROFILE_FAILED: 'CREATE_PROFILE_FAILED',

    DELETE_PROFILE_START: 'DELETE_PROFILE_START',
    DELETE_PROFILE_SUCCESS: 'DELETE_PROFILE_SUCCESS',
    DELETE_PROFILE_FAILED: 'DELETE_PROFILE_FAILED',

    DISABLE_PROFILE: 'DISABLE_PROFILE',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',

    RATE_SHOW_START: 'RATE_SHOW_START',
    RATE_SHOW_SUCCESS: 'RATE_SHOW_SUCCESS',
    RATE_SHOW_FAILED: 'RATE_SHOW_FAILED',

    RATE_RECENTLY_WATCHED_MOVIE_START: 'RATE_RECENTLY_WATCHED_MOVIE_START',
    RATE_RECENTLY_WATCHED_MOVIE_SUCCESS: 'RATE_RECENTLY_WATCHED_MOVIE_SUCCESS',
    RATE_RECENTLY_WATCHED_MOVIE_FAILED: 'RATE_RECENTLY_WATCHED_MOVIE_FAILED',

    REMOVE_TO_RECENT_WATCHES_START: 'REMOVE_TO_RECENT_WATCHES_START',
    REMOVE_TO_RECENT_WATCHES_SUCCESS: 'REMOVE_TO_RECENT_WATCHES_SUCCESS',
    REMOVE_TO_RECENT_WATCHES_FAILED: 'REMOVE_TO_RECENT_WATCHES_FAILED',

    CLEAR_RECENT_WATCHES_START: 'CLEAR_RECENT_WATCHES_START',
    CLEAR_RECENT_WATCHES_SUCCESS: 'CLEAR_RECENT_WATCHES_SUCCESS',
    CLEAR_RECENT_WATCHES_FAILED: 'CLEAR_RECENT_WATCHES_FAILED',

    MANAGE_PIN_CODE_START: 'MANAGE_PIN_CODE_START',
    MANAGE_PIN_CODE_SUCCESS: 'MANAGE_PIN_CODE_SUCCESS',
    MANAGE_PIN_CODE_FAILED: 'MANAGE_PIN_CODE_FAILED',

    MARK_REMINDED_MOVIE_AS_READ_START: 'MARK_REMINDED_MOVIE_AS_READ_START',
    MARK_REMINDED_MOVIE_AS_READ_SUCCESS: 'MARK_REMINDED_MOVIE_AS_READ_SUCCESS',
    MARK_REMINDED_MOVIE_AS_READ_FAILED: 'MARK_REMINDED_MOVIE_AS_READ_FAILED',

    SELECT_PROFILE_START: 'SELECT_PROFILE_START',
    SELECT_PROFILE_SUCCESS: 'SELECT_PROFILE_SUCCESS',
    SELECT_PROFILE_FAILED: 'SELECT_PROFILE_FAILED',

    SET_PROFILE_COUNT_TO_DISABLE: 'SET_PROFILE_COUNT_TO_DISABLE',

    SHOW_SUBSCRIBER_START: 'SHOW_SUBSCRIBER_START',
    SHOW_SUBSCRIBER_SUCCESS: 'SHOW_SUBSCRIBER_SUCCESS',
    SHOW_SUBSCRIBER_FAILED: 'SHOW_SUBSCRIBER_FAILED',

    TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_START: 'TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_START',
    TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_SUCCESS: 'TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_SUCCESS',
    TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_FAILED: 'TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_FAILED',

    TOGGLE_ADD_TO_MY_LIST_START: 'TOGGLE_ADD_TO_MY_LIST_START',
    TOGGLE_ADD_TO_MY_LIST_SUCCESS: 'TOGGLE_ADD_TO_MY_LIST_SUCCESS',
    TOGGLE_ADD_TO_MY_LIST_FAILED: 'TOGGLE_ADD_TO_MY_LIST_FAILED',

    UPDATE_AUTHENTICATED_PROFILE_START: 'UPDATE_AUTHENTICATED_PROFILE_START',
    UPDATE_AUTHENTICATED_PROFILE_SUCCESS: 'UPDATE_AUTHENTICATED_PROFILE_SUCCESS',
    UPDATE_AUTHENTICATED_PROFILE_FAILED: 'UPDATE_AUTHENTICATED_PROFILE_FAILED',

    UPDATE_RECENTLY_WATCHED_AT_POSITION_MILLIS_START: 'UPDATE_RECENTLY_WATCHED_AT_POSITION_MILLIS_START',
    UPDATE_RECENTLY_WATCHED_AT_POSITION_MILLIS_SUCCESS: 'UPDATE_RECENTLY_WATCHED_AT_POSITION_MILLIS_SUCCESS',
    UPDATE_RECENTLY_WATCHED_AT_POSITION_MILLIS_FAILED: 'UPDATE_RECENTLY_WATCHED_AT_POSITION_MILLIS_FAILED',

    CLEAR_ERRORS_PROPERTY: 'CLEAR_ERRORS_PROPERTY',
    UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
    UPDATE_SUBSCRIPTION_DETAILS: 'UPDATE_SUBSCRIPTION_DETAILS'
};

export default ACTION_TYPES