const ACTION_TYPES = 
{
    ADD_TO_RECENT_WATCHES_START: 'ADD_TO_RECENT_WATCHES_START',
    ADD_TO_RECENT_WATCHES_SUCCESS: 'ADD_TO_RECENT_WATCHES_SUCCESS',
    ADD_TO_RECENT_WATCHES_FAILED: 'ADD_TO_RECENT_WATCHES_FAILED',

    CREATE_PROFILE_START: 'CREATE_PROFILE_START',
    CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
    CREATE_PROFILE_FAILED: 'CREATE_PROFILE_FAILED',

    DELETE_PROFILE_START: 'DELETE_PROFILE_START',
    DELETE_PROFILE_SUCCESS: 'DELETE_PROFILE_SUCCESS',
    DELETE_PROFILE_FAILED: 'DELETE_PROFILE_FAILED',

    DOWNLOAD_VIDEO_START: 'DOWNLOAD_VIDEO_START',
    DOWNLOAD_VIDEO_SUCCESS: 'DOWNLOAD_VIDEO_SUCCESS',
    DOWNLOAD_VIDEO_FAILED: 'DOWNLOAD_VIDEO_FAILED',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',

    RATE_SHOW_START: 'RATE_SHOW_START',
    RATE_SHOW_SUCCESS: 'RATE_SHOW_SUCCESS',
    RATE_SHOW_FAILED: 'RATE_SHOW_FAILED',

    RATE_RECENTLY_WATCHED_MOVIE_START: 'RATE_RECENTLY_WATCHED_MOVIE_START',
    RATE_RECENTLY_WATCHED_MOVIE_SUCCESS: 'RATE_RECENTLY_WATCHED_MOVIE_SUCCESS',
    RATE_RECENTLY_WATCHED_MOVIE_FAILED: 'RATE_RECENTLY_WATCHED_MOVIE_FAILED',
    
    REMOVE_TO_MY_DOWNLOADS_START: 'REMOVE_TO_MY_DOWNLOADS_START',
    REMOVE_TO_MY_DOWNLOADS_SUCCESS: 'REMOVE_TO_MY_DOWNLOADS_SUCCESS',
    REMOVE_TO_MY_DOWNLOADS_FAILED: 'REMOVE_TO_MY_DOWNLOADS_FAILED',

    REMOVE_TO_RECENT_WATCHES_START: 'REMOVE_TO_RECENT_WATCHES_START',
    REMOVE_TO_RECENT_WATCHES_SUCCESS: 'REMOVE_TO_RECENT_WATCHES_SUCCESS',
    REMOVE_TO_RECENT_WATCHES_FAILED: 'REMOVE_TO_RECENT_WATCHES_FAILED',

    SELECT_PROFILE_START: 'SELECT_PROFILE_START',
    SELECT_PROFILE_SUCCESS: 'SELECT_PROFILE_SUCCESS',
    SELECT_PROFILE_FAILED: 'SELECT_PROFILE_FAILED',

    TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_START: 'TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_START',
    TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_SUCCESS: 'TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_SUCCESS',
    TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_FAILED: 'TOGGLE_REMIND_ME_OF_COMING_SOON_SHOW_FAILED',

    TOGGLE_ADD_TO_MY_LIST_START: 'TOGGLE_ADD_TO_MY_LIST_START',
    TOGGLE_ADD_TO_MY_LIST_SUCCESS: 'TOGGLE_ADD_TO_MY_LIST_SUCCESS',
    TOGGLE_ADD_TO_MY_LIST_FAILED: 'TOGGLE_ADD_TO_MY_LIST_FAILED',

    UPDATE_AUTHENTICATED_PROFILE_START: 'UPDATE_AUTHENTICATED_PROFILE_START',
    UPDATE_AUTHENTICATED_PROFILE_SUCCESS: 'UPDATE_AUTHENTICATED_PROFILE_SUCCESS',
    UPDATE_AUTHENTICATED_PROFILE_FAILED: 'UPDATE_AUTHENTICATED_PROFILE_FAILED',

    VIEW_DOWNLOADS_START: 'VIEW_DOWNLOADS_START',
    VIEW_DOWNLOADS_SUCCESS: 'VIEW_DOWNLOADS_SUCCESS',
    VIEW_DOWNLOADS_FAILED: 'VIEW_DOWNLOADS_FAILED',

    CLEAR_ERRORS_PROPERTY: 'CLEAR_ERRORS_PROPERTY'
};

export default ACTION_TYPES