const ACTION_TYPES = {
    TOGGLE_TAB_BAR_START: 'TOGGLE_TAB_BAR_START',
    TOGGLE_TAB_BAR_SUCCESS: 'TOGGLE_TAB_BAR_SUCCESS',
    TOGGLE_TAB_BAR_FAILED: 'TOGGLE_TAB_BAR_FAILED',
};

export default ACTION_TYPES