const ACTION_TYPES = {
    GET_COMING_SOON_SHOWS_START: 'GET_COMING_SOON_SHOWS_START',
    GET_COMING_SOON_SHOWS_SUCCESS: 'GET_COMING_SOON_SHOWS_SUCCESS',
    GET_COMING_SOON_SHOWS_FAILED: 'GET_COMING_SOON_SHOWS_FAILED'
};

export default ACTION_TYPES