const ACTION_TYPES = {
    GET_COMING_SOON_MOVIES_START: 'GET_COMING_SOON_MOVIES_START',
    GET_COMING_SOON_MOVIES_SUCCESS: 'GET_COMING_SOON_MOVIES_SUCCESS',
    GET_COMING_SOON_MOVIES_FAILED: 'GET_COMING_SOON_MOVIES_FAILED'
};

export default ACTION_TYPES