const ACTION_TYPES = {
    GET_COMING_SOON_MOVIES_START: 'GET_COMING_SOON_MOVIES_START',
    GET_COMING_SOON_MOVIES_SUCCESS: 'GET_COMING_SOON_MOVIES_SUCCESS',
    GET_COMING_SOON_MOVIES_FAILED: 'GET_COMING_SOON_MOVIES_FAILED',

    CREATE_COMING_SOON_MOVIE: 'CREATE_COMING_SOON_MOVIE',
    DELETE_COMING_SOON_MOVIE_BY_ID: 'DELETE_COMING_SOON_MOVIE_BY_ID',

    INCREMENT_NEW_COMING_SOON_MOVIE_COUNT: 'INCREMENT_NEW_COMING_SOON_MOVIE_COUNT',

    VIEW_COMING_SOON_MOVIES: 'VIEW_COMING_SOON_MOVIES',
};

export default ACTION_TYPES